### PR TITLE
docs: add unraid documentation

### PR DESCRIPTION
**Pull request by nwithan8**

### CODE REVIEW

**Review by RaunoT — APPROVED** [review]
Thanks for this!

**Comment by RaunoT** [comment]
@nwithan8 could you please have a look if manually copying the `settings.json` on Unraid is still relevant/required on the latest `3.x.x` release

**Comment by nwithan8** [comment]
> @nwithan8 could you please have a look if manually copying the `settings.json` on Unraid is still relevant/required on the latest `3.x.x` release?

Sorry about the late reply. Starting from complete scratch using the "latest" Docker tag (which is equivalent to v4.0.1 at time of writing), it seems like the application can read and write a `settings.json` file to the host system without one needing to be there before initial boot. I'll remove that note from the Unraid template.

**Comment by RaunoT** [comment]
Thanks for taking a look! I will ammend the readme here also.

**Pull request merged**
